In [7]:
from sklearn.externals import joblib
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


tcontext = 120
# Load features and labels
features = np.load('features_tcontext_' + str(tcontext) + '_frameSize_1024.npz')
features = features['a']
features += np.finfo(np.float32).eps
labels = features[:,-1].astype(int)
features = features[:, :features.shape[1] - 1]
        
best_xgb = './tcontext_120/models/xgb/xgb_learningRate_0.5_kBestFeatures_86.sav'
clf_xgb = joblib.load(best_xgb)

best_svm = './tcontext_120/models/svm/svm_86_best_features.sav'
clf_svm = joblib.load(best_svm)

features_train, features_val, labels_train, labels_val = train_test_split(features, labels, test_size=0.2, random_state = 42)

pred_xgb = clf_xgb.predict(features_val)
pred_svm = clf_svm.predict(features_val)



In [10]:
print('XGB model\n')
print('Confusion matrix: \n\n')
print(str(confusion_matrix(labels_val,pred_xgb)))
print('\n\n')
print('Classification report: \n\n')
print(str(classification_report(labels_val,pred_xgb)))
print('\n\n')
print('Accuracy: ' + str(accuracy_score(labels_val, pred_xgb)))
print('\n\n\n\n\n')

print('SVM model\n')
print('Confusion matrix: \n\n')
print(str(confusion_matrix(labels_val,pred_svm)))
print('\n\n')
print('Classification report: \n\n')
print(str(classification_report(labels_val,pred_svm)))
print('\n\n')
print('Accuracy: ' + str(accuracy_score(labels_val, pred_svm)))



XGB model

Confusion matrix: 


[[ 5241   960   241    49]
 [  942 12352   380    67]
 [  314   627  9318    23]
 [  135   249   115  9738]]



Classification report: 


              precision    recall  f1-score   support

           0       0.79      0.81      0.80      6491
           1       0.87      0.90      0.88     13741
           2       0.93      0.91      0.92     10282
           3       0.99      0.95      0.97     10237

   micro avg       0.90      0.90      0.90     40751
   macro avg       0.89      0.89      0.89     40751
weighted avg       0.90      0.90      0.90     40751




Accuracy: 0.899339893499546






SVM model

Confusion matrix: 


[[ 4742  1566    93    90]
 [ 1364 12108   159   110]
 [  183  1241  8826    32]
 [  203   480   129  9425]]



Classification report: 


              precision    recall  f1-score   support

           0       0.73      0.73      0.73      6491
           1       0.79      0.88      0.83     13741
           2       0.96  